import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/MyComponents/header/header";
import Footer from "./components/MyComponents/footer/footer";

import "@fontsource/poppins"; // Defaults to 400
import "@fontsource/poppins/700.css"; // If you need bold text

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Central Territory Plumbing Pty Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="mb-12 fixed md:mb-24 z-50"> <Header/></div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
